{"assignees":[{"id":"MDQ6VXNlcjExNjY0MjU5","login":"galipremsagar","name":"GALI PREM SAGAR"}],"author":{"id":"MDQ6VXNlcjExMjY1Mw==","is_bot":false,"login":"mattf","name":"Matthew Farrellee"},"body":"**Steps/Code to reproduce bug**\r\n```\r\n$ python3.9 -m IPython\r\nPython 3.9.14 (main, Sep  7 2022, 23:43:48) \r\nType 'copyright', 'credits' or 'license' for more information\r\nIPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.\r\n\r\nIn [1]: import pandas as pd, cudf\r\n\r\nIn [2]: pd.__version__, cudf.__version__\r\nOut[2]: ('1.4.4', '22.10.00a+392.g1558403753')\r\n\r\nIn [3]: pdf = pd.DataFrame({'a': ['123_1']})\r\n\r\nIn [4]: pdf.a.astype('int32')\r\nOut[4]: \r\n0    1231\r\nName: a, dtype: int32\r\n\r\nIn [5]: cdf = cudf.DataFrame({'a': ['123_1']})\r\n\r\nIn [6]: cdf.a.astype('int32')\r\n---------------------------------------------------------------------------\r\nValueError                                Traceback (most recent call last)\r\nCell In [6], line 1\r\n----> 1 cdf.a.astype('int32')\r\n\r\n...\r\n\r\nFile ~/.local/lib/python3.9/site-packages/cudf/core/column/string.py:5314, in StringColumn.as_numerical_column(self, dtype, **kwargs)\r\n   5312 if out_dtype.kind in {\"i\", \"u\"}:\r\n   5313     if not libstrings.is_integer(string_col).all():\r\n-> 5314         raise ValueError(\r\n   5315             \"Could not convert strings to integer \"\r\n   5316             \"type due to presence of non-integer values.\"\r\n   5317         )\r\n   5318 elif out_dtype.kind == \"f\":\r\n   5319     if not libstrings.is_float(string_col).all():\r\n\r\nValueError: Could not convert strings to integer type due to presence of non-integer values.\r\n```\r\n\r\n**Expected behavior**\r\n`cudf` to produce the same result as `pandas`\r\n\r\n\r\n**Environment overview**\r\n```\r\n$ nvidia-smi \r\nWed Nov  2 16:48:53 2022       \r\n+-----------------------------------------------------------------------------+\r\n| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |\r\n|-------------------------------+----------------------+----------------------+\r\n| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\r\n| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\r\n|                               |                      |               MIG M. |\r\n|===============================+======================+======================|\r\n|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |\r\n| N/A   56C    P8    15W /  70W |      0MiB / 15360MiB |      0%      Default |\r\n|                               |                      |                  N/A |\r\n+-------------------------------+----------------------+----------------------+\r\n                                                                               \r\n+-----------------------------------------------------------------------------+\r\n| Processes:                                                                  |\r\n|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |\r\n|        ID   ID                                                   Usage      |\r\n|=============================================================================|\r\n|  No running processes found                                                 |\r\n+-----------------------------------------------------------------------------+\r\n```","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5NipUB","author":{"login":"shwina"},"authorAssociation":"CONTRIBUTOR","body":"As a workaround, you could remove `_` from your strings:\r\n\r\n```python\r\nIn [5]: s = cudf.Series(['1_000', '20_000'])\r\n\r\nIn [6]: s.to_pandas().astype('int32')\r\nOut[6]: \r\n0     1000\r\n1    20000\r\ndtype: int32\r\n\r\nIn [7]: s.str.replace('_', '').astype('int32')\r\nOut[7]: \r\n0     1000\r\n1    20000\r\ndtype: int32\r\n\r\n```","createdAt":"2022-11-02T17:06:08Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12047#issuecomment-1300927745","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5Nj0N9","author":{"login":"galipremsagar"},"authorAssociation":"CONTRIBUTOR","body":"@davidwendt would it be possible for the `libstrings.is_integer` API's to handle `_` in strings? or do you think we should sanitize strings before we call `libstrings.is_integer`?","createdAt":"2022-11-02T20:55:17Z","includesCreatedEdit":true,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12047#issuecomment-1301234557","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5NkKXD","author":{"login":"davidwendt"},"authorAssociation":"CONTRIBUTOR","body":"This seems to be python-specific. C++ does not support `_` for string-to-integer conversion.\r\nhttps://godbolt.org/z/ocGfob1EG\r\nlibcudf aligns with C++ as much as possible so I think you will have to sanitize the strings beforehand.\r\n","createdAt":"2022-11-02T21:37:59Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12047#issuecomment-1301325251","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5NkLeQ","author":{"login":"galipremsagar"},"authorAssociation":"CONTRIBUTOR","body":"makes sense, thanks @davidwendt ","createdAt":"2022-11-02T21:40:02Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/12047#issuecomment-1301329808","viewerDidAuthor":false}],"createdAt":"2022-11-02T16:53:58Z","id":"I_kwDOBWUGps5VcSra","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDE2MzMyOTQ4","name":"good first issue","description":"Good for newcomers","color":"7057ff"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":12047,"projectCards":[{"project":{"name":"Bug Squashing"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] cudf astype('int32') behavior does not match pandas","updatedAt":"2024-05-15T17:42:23Z","url":"https://github.com/rapidsai/cudf/issues/12047"}
