{"assignees":[],"author":{"id":"MDQ6VXNlcjEwNjQ3MDgy","is_bot":false,"login":"mroeschke","name":"Matthew Roeschke"},"body":"**Describe the bug**\r\nDataFrame.pop removes column name\r\n\r\n**Steps/Code to reproduce bug**\r\n```python\r\nIn [1]: import cudf\r\n\r\nIn [2]: df = cudf.DataFrame({\"a\": [1., 2.]})\r\n\r\nIn [3]: df.index.name = \"baz\"\r\n\r\nIn [4]: df\r\nOut[4]: \r\n       a\r\nbaz     \r\n0    1.0\r\n1    2.0\r\n\r\nIn [5]: df[\"foo\"] = \"bar\"\r\n\r\nIn [6]: df\r\nOut[6]: \r\n       a  foo\r\nbaz          \r\n0    1.0  bar\r\n1    2.0  bar\r\n\r\nIn [7]: df.pop(\"foo\")\r\nOut[7]: \r\nbaz\r\n0    bar\r\n1    bar\r\nName: foo, dtype: object\r\n\r\nIn [8]: df.columns.name # should be \"baz\"\r\n\r\nIn [9]: df.columns\r\nOut[9]: Index(['a'], dtype='object')\r\n```\r\n\r\n**Expected behavior**\r\n```python\r\nIn [8]: df.columns.name\r\n\"baz\"\r\n```\r\n\r\n**Environment overview (please complete the following information)**\r\n - Environment location: Bare-metal\r\n - Method of cuDF install: conda\r\n   - If method of install is [Docker], provide `docker pull` & `docker run` commands used\r\n\r\n**Environment details**\r\nPlease run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details\r\n\r\n**Additional context**\r\nAdd any other context about the problem here.\r\n","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps5lWFoG","author":{"login":"galipremsagar"},"authorAssociation":"CONTRIBUTOR","body":"@mroeschke Is the example you provided for a different issue? Or were you referring to this:\r\n```python\r\nIn [37]: df = cudf.DataFrame({\"a\": [1., 2.]})\r\n\r\nIn [38]: df\r\nOut[38]: \r\n     a\r\n0  1.0\r\n1  2.0\r\n\r\nIn [39]: df.columns.name = \"baz\"\r\n\r\nIn [40]: df\r\nOut[40]: \r\n     a\r\n0  1.0\r\n1  2.0\r\n\r\nIn [41]: df.columns\r\nOut[41]: Index(['a'], dtype='object')\r\n\r\n.\r\n.\r\n.\r\n```","createdAt":"2023-08-31T02:40:44Z","includesCreatedEdit":true,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/14012#issuecomment-1700289030","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5lZ2CW","author":{"login":"mroeschke"},"authorAssociation":"CONTRIBUTOR","body":"Ah yes my example in the OP is incorrect. Yeah I think the core issue is that `column.name` cannot be assigned","createdAt":"2023-08-31T15:34:42Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/14012#issuecomment-1701273750","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5lhKPK","author":{"login":"mroeschke"},"authorAssociation":"CONTRIBUTOR","body":"@galipremsagar is there a reason why `cudf.DataFrame`'s return pandas objects for `df.columns`? I think this might be the limitation why the name cannot be set\r\n\r\n```\r\nIn [1]: import cudf\r\n\r\nIn [2]: df = cudf.DataFrame({\"a\": [1., 2.]})\r\n\r\nIn [8]: type(df.columns)\r\nOut[8]: pandas.core.indexes.base.Index\r\n\r\nIn [9]: type(df.index)\r\nOut[9]: cudf.core.index.RangeIndex\r\n```","createdAt":"2023-09-01T18:51:00Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/14012#issuecomment-1703191498","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps5lvzd_","author":{"login":"vyasr"},"authorAssociation":"CONTRIBUTOR","body":"I believe it is because most operations involving column names occur on the host, not on device. Storing the column names in a cudf Index would require constant H2D copies. @shwina may be able to provide more of the history here, but I do agree that this choice can sometimes cause confusion and make certain aspects of implementation harder.","createdAt":"2023-09-05T17:34:49Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/14012#issuecomment-1707030399","viewerDidAuthor":false}],"createdAt":"2023-08-30T22:48:25Z","id":"I_kwDOBWUGps5vuk-i","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":14012,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Cannot assign DataFrame.column.name","updatedAt":"2023-09-05T17:34:49Z","url":"https://github.com/rapidsai/cudf/issues/14012"}
