{"assignees":[],"author":{"id":"MDQ6VXNlcjEzNTIxMDA4","is_bot":false,"login":"isVoid","name":"Michael Wang"},"body":"Currently we depend on `infer_dtype_from_object` in `utils/dtype.py`:\r\nhttps://github.com/rapidsai/cudf/blob/9510ef6a97102782906423ff5fd132c0e4bb08fd/python/cudf/cudf/utils/dtypes.py#L11\r\n\r\nSince `infer_dtype_from_object` is not publicly documented in pandas, it is arguably better to switch to the [public documented](https://pandas.pydata.org/docs/reference/api/pandas.api.types.infer_dtype.html) version of `infer_dtype`.\r\n\r\nThe switch is not trivial. As two functions does not always have the same behavior:\r\n```python\r\n>>> infer_dtype(\"timedelta64\")\r\n'string'\r\n>>> infer_dtype_from_object(\"timedelta64\")\r\n<class 'numpy.timedelta64'>\r\n```\r\n```python\r\n>>> infer_dtype(np.datetime64)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"pandas/_libs/lib.pyx\", line 1350, in pandas._libs.lib.infer_dtype\r\n  File \"pandas/_libs/lib.pyx\", line 1229, in pandas._libs.lib._try_infer_map\r\nAttributeError: 'getset_descriptor' object has no attribute 'name'\r\n>>> infer_dtype_from_object(np.datetime64)\r\n<class 'numpy.datetime64'>\r\n```","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps46lBHT","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.","createdAt":"2021-11-30T16:07:47Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8623#issuecomment-982782419","viewerDidAuthor":false}],"createdAt":"2021-06-29T00:32:40Z","id":"MDU6SXNzdWU5MzIxMDAzMDY=","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NjE=","name":"feature request","description":"New feature or request","color":"a2eeef"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":6,"title":"cuDF Python Refactoring","description":"Refactor Python layers to improve performance, robustness, and extensibility. Ongoing development is being guided by the roadmap and evolving development guide.","dueOn":null},"number":8623,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[FEA] Replace `infer_dtype_from_object` with `infer_dtype`","updatedAt":"2024-02-23T18:42:22Z","url":"https://github.com/rapidsai/cudf/issues/8623"}
