{"assignees":[],"author":{"id":"MDQ6VXNlcjExMjY1Mw==","is_bot":false,"login":"mattf","name":"Matthew Farrellee"},"body":"**Describe the bug**\r\nusing `import cudf as pd`\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\n>>> import cudf as pd\r\n>>> import numpy as np\r\n\r\n>>> df = pd.DataFrame({'a': ['one', 'two', 'three', 'four', np.nan, None, 'NA'], 'b': ['this', 'that', 'the', 'other', np.nan, np.nan, 'Missing'], 'c': ['something', 'or', 'other', None, np.nan, 'hmm', 'NA'], 'd': ['00', '01', '02', '03', None, None, 'Missing']})\r\n>>> df\r\n       a        b          c        d\r\n0    one     this  something       00\r\n1    two     that         or       01\r\n2  three      the      other       02\r\n3   four    other       <NA>       03\r\n4   <NA>     <NA>       <NA>     <NA>\r\n5   <NA>     <NA>        hmm     <NA>\r\n6     NA  Missing         NA  Missing\r\n\r\n>>> df.dropna(axis='index')\r\n/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py:1165: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.\r\n  mask = pd.Series(mask)\r\nEmpty DataFrame\r\nColumns: []\r\nIndex: [0, 1, 2, 3, 4, 5, 6]\r\n>>> df.to_pandas().dropna(axis='index')\r\n       a        b          c        d\r\n0    one     this  something       00\r\n1    two     that         or       01\r\n2  three      the      other       02\r\n6     NA  Missing         NA  Missing\r\n```\r\n\r\n**Environment overview (please complete the following information)**\r\n - rapidsai/rapidsai-nightly:cuda11.5-runtime-ubuntu20.04-py3.8\r\n - sha256:4a69370ad40f47a71404805fe2b1dd0a5cf28d7f6a5d4dd1cad419f8a3c8ce5f\r\n - 30 jan 2023\r\n\r\n![Screenshot from 2023-01-30 14-12-11](https://user-images.githubusercontent.com/112653/215572351-96fdd5bc-b96a-47ed-a55b-f84e5cbd9603.png)\r\n![Screenshot from 2023-01-30 14-12-02](https://user-images.githubusercontent.com/112653/215572362-8705fc0a-9ae8-4e94-a62f-5f99a32ff235.png)\r\n\r\n","closed":false,"closedAt":null,"comments":[],"createdAt":"2023-01-30T19:13:24Z","id":"I_kwDOBWUGps5dKjbn","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":12650,"projectCards":[{"project":{"name":"Bug Squashing"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] DataFrame.dropna does not support axis='index' results in mismatch w/ pandas","updatedAt":"2023-06-06T04:32:10Z","url":"https://github.com/rapidsai/cudf/issues/12650"}
