{"assignees":[{"id":"MDQ6VXNlcjExNjY0MjU5","login":"galipremsagar","name":"GALI PREM SAGAR"}],"author":{"id":"MDQ6VXNlcjQxNDAxNTY2","is_bot":false,"login":"Iroy30","name":""},"body":"**Describe the bug**\r\nDrop function for Multicolumn index doesn't work as expected\r\nThe error I get is: 'One or more values not found in axis'\r\n\r\n**Steps/Code to reproduce bug**\r\n```python\r\nimport cudf\r\ndf=cudf.DataFrame()\r\ndf['src_lat']=[-46.0,-46.0,-46.0, -34.0,-34.0,-34.0, 11.5, 11.5, 11.5]; df['src_long']=df['src_lat']+1\r\ndf['dst_lat']=[-46.0, -34.0,11.5,-46.0, -34.0,11.5,-46.0, -34.0,11.5];df['dst_long']=df['dst_lat']+1\r\ndf['val']=[0.1,0.2,0.1,0.3,0.2,0.1,0.3,0.3,0.1]\r\ndf = df.pivot(index=['src_lat', 'src_long'], columns=['dst_lat', 'dst_long'], values=['val'])\r\ndf.columns = df.index\r\ndf.drop([(11.5, 12.5), (-46.0, -45.0)])\r\n```\r\n","closed":false,"closedAt":null,"comments":[{"id":"IC_kwDOBWUGps45xqRM","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-30d` due to no recent activity in the past 30 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed. This issue will be labeled `inactive-90d` if there is no activity in the next 60 days.","createdAt":"2021-11-15T21:04:41Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8987#issuecomment-969319500","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps495X3d","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.","createdAt":"2022-02-13T22:03:49Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8987#issuecomment-1038450141","viewerDidAuthor":false},{"id":"IC_kwDOBWUGps59s4By","author":{"login":"vyasr"},"authorAssociation":"CONTRIBUTOR","body":"This still fails for me, but now it fails even earlier, on the pivot call:\r\n\r\n<details><summary>Traceback</summary>\r\n\r\n```\r\nIn [1]: import cudf                        \r\n   ...: df=cudf.DataFrame()                                                                           \r\n   ...: df['src_lat']=[-46.0,-46.0,-46.0, -34.0,-34.0,-34.0, 11.5, 11.5, 11.5]; df['src_long']=df['src_lat']+1\r\n   ...: df['dst_lat']=[-46.0, -34.0,11.5,-46.0, -34.0,11.5,-46.0, -34.0,11.5];df['dst_long']=df['dst_lat']+1\r\n   ...: df['val']=[0.1,0.2,0.1,0.3,0.2,0.1,0.3,0.3,0.1]                                  \r\n   ...: df = df.pivot(index=['src_lat', 'src_long'], columns=['dst_lat', 'dst_long'], values=['val'])\r\n   ...: df.columns = df.index\r\n   ...: df.drop([(11.5, 12.5), (-46.0, -45.0)])                                                       \r\n---------------------------------------------------------------------------\r\nValueError                                Traceback (most recent call last)\r\nCell In[1], line 6         \r\n      4 df['dst_lat']=[-46.0, -34.0,11.5,-46.0, -34.0,11.5,-46.0, -34.0,11.5];df['dst_long']=df['dst_lat']+1\r\n      5 df['val']=[0.1,0.2,0.1,0.3,0.2,0.1,0.3,0.3,0.1]                                         \r\n----> 6 df = df.pivot(index=['src_lat', 'src_long'], columns=['dst_lat', 'dst_long'], values=['val'])\r\n      7 df.columns = df.index\r\n      8 df.drop([(11.5, 12.5), (-46.0, -45.0)])\r\n                                                   \r\nFile ~/.conda/envs/rapids/lib/python3.10/site-packages/nvtx/nvtx.py:116, in annotate.__call__.<locals>.inner(*args, **kwargs)\r\n    113 @wraps(func)         \r\n    114 def inner(*args, **kwargs):\r\n    115     libnvtx_push_range(self.attributes, self.domain.handle)\r\n--> 116     result = func(*args, **kwargs)\r\n    117     libnvtx_pop_range(self.domain.handle)                                                                                                                                                           \r\n    118     return result\r\n\r\nFile ~/cudf/python/cudf/cudf/core/dataframe.py:7300, in DataFrame.pivot(self, columns, index, values)\r\n   7297 @_cudf_nvtx_annotate\r\n   7298 @copy_docstring(reshape.pivot)\r\n   7299 def pivot(self, *, columns, index=no_default, values=no_default):\r\n-> 7300     return cudf.core.reshape.pivot(\r\n   7301         self, index=index, columns=columns, values=values\r\n   7302     )\r\n\r\nFile ~/cudf/python/cudf/cudf/core/reshape.py:1054, in pivot(data, columns, index, values)\r\n   1052     index = df.index\r\n   1053 else:\r\n-> 1054     index = cudf.core.index.Index(df.loc[:, index])\r\n   1055 columns = cudf.Index(df.loc[:, columns])\r\n   1057 # Create a DataFrame composed of columns from both\r\n   1058 # columns and index\r\n\r\nFile ~/cudf/python/cudf/cudf/core/index.py:78, in IndexMeta.__call__(cls, data, *args, **kwargs)\r\n     76 def __call__(cls, data, *args, **kwargs):\r\n     77     if cls is Index:\r\n---> 78         return as_index(\r\n     79             arbitrary=data,\r\n     80             *args,\r\n     81             **kwargs,\r\n     82         )\r\n     83     return super().__call__(data, *args, **kwargs)\r\n\r\nFile ~/.conda/envs/rapids/lib/python3.10/site-packages/nvtx/nvtx.py:116, in annotate.__call__.<locals>.inner(*args, **kwargs)\r\n    113 @wraps(func)\r\n    114 def inner(*args, **kwargs):\r\n    115     libnvtx_push_range(self.attributes, self.domain.handle)\r\n--> 116     result = func(*args, **kwargs)\r\n    117     libnvtx_pop_range(self.domain.handle)\r\n    118     return result\r\n\r\nFile ~/cudf/python/cudf/cudf/core/index.py:3061, in as_index(arbitrary, nan_as_null, copy, name, dtype)\r\n   3057     return cudf.MultiIndex.from_pandas(\r\n   3058         arbitrary.copy(deep=copy), nan_as_null=nan_as_null\r\n   3059     )\r\n   3060 elif isinstance(arbitrary, cudf.DataFrame) or is_scalar(arbitrary):\r\n-> 3061     raise ValueError(\"Index data must be 1-dimensional and list-like\")\r\n   3062 else:\r\n   3063     return as_index(\r\n   3064         column.as_column(arbitrary, dtype=dtype, nan_as_null=nan_as_null),\r\n   3065         copy=copy,\r\n   3066         name=name,\r\n   3067         dtype=dtype,\r\n   3068     )\r\n\r\nValueError: Index data must be 1-dimensional and list-like\r\n```\r\n</details>\r\n","createdAt":"2024-05-13T22:34:29Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/8987#issuecomment-2108915826","viewerDidAuthor":false}],"createdAt":"2021-08-06T15:48:46Z","id":"MDU6SXNzdWU5NjI4NTM4MTI=","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":8987,"projectCards":[{"project":{"name":"Bug Squashing"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] Drop function for Multicolumn index doesn't work","updatedAt":"2024-05-13T22:34:30Z","url":"https://github.com/rapidsai/cudf/issues/8987"}
