{"assignees":[{"id":"MDQ6VXNlcjExNjY0MjU5","login":"galipremsagar","name":"GALI PREM SAGAR"}],"author":{"id":"MDQ6VXNlcjEyMTY5NTU=","is_bot":false,"login":"oliverholworthy","name":"Oliver Holworthy"},"body":"**Describe the bug**\r\n\r\n`is_list_like` does not match pandas equivalent for cupy array objects\r\n\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.api.types.is_list_like.html\r\n\r\n**Steps/Code to reproduce bug**\r\n\r\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\nimport cudf\r\nimport cupy as cp\r\n\r\npd.api.types.is_list_like(np.array([1]))  # => True\r\npd.api.types.is_list_like(cp.array([1]))  # => True\r\n\r\ncudf.api.types.is_list_like(np.array([1]))  # => True\r\ncudf.api.types.is_list_like(cp.array([1]))  # => False\r\n```\r\n\r\n**Expected behavior**\r\n\r\nI'd expect `is_list_like` to return True matching the equivalent pandas function when called with a cupy or numpy array containing a list of values\r\n\r\n```python\r\ncudf.api.types.is_list_like(cp.array([1]))  # => True\r\n```\r\n\r\n**Environment overview (please complete the following information)**\r\n - Environment location: docker\r\n - Method of cuDF install: pip\r\n\r\n","closed":false,"closedAt":null,"comments":[],"createdAt":"2023-03-20T15:04:26Z","id":"I_kwDOBWUGps5hSugN","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":12975,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] `is_list_like` does not match pandas equivalent for cupy arrays","updatedAt":"2023-06-05T18:24:19Z","url":"https://github.com/rapidsai/cudf/issues/12975"}
