{"assignees":[{"id":"MDQ6VXNlcjExNjY0MjU5","login":"galipremsagar","name":"GALI PREM SAGAR"}],"author":{"id":"MDQ6VXNlcjExMjY1Mw==","is_bot":false,"login":"mattf","name":"Matthew Farrellee"},"body":"**Describe the bug**\r\nworking with `import cudf as pd`\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\n>>> import cudf, pandas, numpy\r\n>>> cudf.__version__\r\n'23.02.00a+310.g58e0fde346'\r\n>>> pandas.__version__\r\n'1.5.3'\r\n\r\n>>> cudf.Series([1, 2, numpy.nan]).replace(numpy.nan, -1)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/opt/conda/envs/rapids/lib/python3.8/contextlib.py\", line 75, in inner\r\n    return func(*args, **kwds)\r\n  File \"/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py\", line 2180, in replace\r\n    return super().replace(to_replace, value, *args, **kwargs)\r\n  File \"/opt/conda/envs/rapids/lib/python3.8/contextlib.py\", line 75, in inner\r\n    return func(*args, **kwds)\r\n  File \"/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/indexed_frame.py\", line 765, in replace\r\n    copy_data[name] = col.find_and_replace(\r\n  File \"/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py\", line 483, in find_and_replace\r\n    to_replace_col = _normalize_find_and_replace_input(\r\n  File \"/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py\", line 771, in _normalize_find_and_replace_input\r\n    col_to_normalize_casted = input_column_dtype.type(\r\nValueError: cannot convert float NaN to integer\r\n>>> pandas.Series([1, 2, numpy.nan]).replace(numpy.nan, -1)\r\n0    1.0\r\n1    2.0\r\n2   -1.0\r\ndtype: float64\r\n```","closed":false,"closedAt":null,"comments":[],"createdAt":"2023-02-07T13:40:55Z","id":"I_kwDOBWUGps5d1sHy","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"},{"id":"MDU6TGFiZWwxMDEzOTg3MzUy","name":"0 - Backlog","description":"In queue waiting for assignment","color":"d4c5f9"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":{"number":5,"title":"Pandas API Alignment and Coverage","description":"","dueOn":null},"number":12720,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] NA handling inconsistent in DataFrame/Series.replace","updatedAt":"2023-06-06T05:04:40Z","url":"https://github.com/rapidsai/cudf/issues/12720"}
