{"assignees":[],"author":{"id":"MDQ6VXNlcjExMjY5ODE=","is_bot":false,"login":"wence-","name":"Lawrence Mitchell"},"body":"**Describe the bug**\r\n\r\n```python\r\nimport cudf\r\n\r\nleft = cudf.MultiIndex.from_tuples([(1,)])\r\nright = cudf.MultiIndex.from_tuples([(1.0,)])\r\n\r\nprint(left.equals(right)) # => False\r\n\r\nprint(left.to_pandas().equals(right.to_pandas())) # => True\r\n```\r\n\r\n**Expected behavior**\r\n\r\nThis should match pandas. Note that `Index.equals` does do dtype casting.","closed":false,"closedAt":null,"comments":[],"createdAt":"2023-12-05T15:58:40Z","id":"I_kwDOBWUGps54yora","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NTk=","name":"bug","description":"Something isn't working","color":"d73a4a"}],"milestone":null,"number":14569,"projectCards":[],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[BUG] `MultiIndex.equals` does not match pandas for numerical indexes with unequal dtypes","updatedAt":"2024-03-04T20:26:28Z","url":"https://github.com/rapidsai/cudf/issues/14569"}
