{"assignees":[{"id":"MDQ6VXNlcjMxOTA0MDU=","login":"shwina","name":"Ashwin Srinath"}],"author":{"id":"MDQ6VXNlcjY3MzA5NzQ1","is_bot":false,"login":"vivanov10","name":""},"body":"\r\n**Is your feature request related to a problem? Please describe.**\r\n\r\ncuDF doesn't work out of the box with `NamedTuple` when constructing a `DataFrame`\r\n\r\n**Describe the solution you'd like**\r\n\r\nAdd support for `NamedTuple`\r\n\r\n**Describe alternatives you've considered**\r\n\r\nFirst, create a `NamedTuple` object:\r\n\r\n```python\r\nfrom typing import NamedTuple, Optional, List\r\nclass ModelPrediction(NamedTuple):\r\n    suspicious: Optional[bool]\r\n    confidence: Optional[float]\r\n    prediction: Optional[List[float]]\r\n\r\noutputs = [ModelPrediction(suspicious=True, confidence=0.1, prediction=60), ModelPrediction(suspicious=False, confidence=0.6, prediction=40), ModelPrediction(suspicious=True, confidence=0.8, prediction=30)]\r\n```\r\n\r\ncuDF workaround:\r\n```python\r\nimport cudf as pd\r\npd.DataFrame(list(iter(outputs)), columns=ModelPrediction.__annotations__.keys())\r\n```\r\n\r\n**Additional context**\r\n\r\nPandas works out of the box:\r\n```python\r\nimport pandas as pd\r\npd.DataFrame(iter(outputs))\r\n```\r\n\r\nwhile cuDF produces a DataFrame with column names missing:\r\n```python\r\nimport cudf as pd\r\npd.DataFrame(list(iter(outputs))) # column names missing\r\n\r\n```\r\n\r\nOutput:\r\n```\r\nsuspicious\tconfidence\tprediction\r\n0\tTrue\t0.1\t60\r\n1\tFalse\t0.6\t40\r\n2\tTrue\t0.8\t30\r\n```","closed":false,"closedAt":null,"comments":[{"id":"MDEyOklzc3VlQ29tbWVudDc5ODk2MjM3Ng==","author":{"login":"github-actions"},"authorAssociation":"NONE","body":"This issue has been labeled `inactive-90d` due to no recent activity in the past 90 days. Please close this issue if no further response or action is needed. Otherwise, please respond with a comment indicating any updates or changes to the original issue and/or confirm this issue still needs to be addressed.","createdAt":"2021-03-14T19:12:47Z","includesCreatedEdit":false,"isMinimized":false,"minimizedReason":"","reactionGroups":[],"url":"https://github.com/rapidsai/cudf/issues/5550#issuecomment-798962376","viewerDidAuthor":false}],"createdAt":"2020-06-23T07:22:34Z","id":"MDU6SXNzdWU2NDM1OTc0MDQ=","labels":[{"id":"MDU6TGFiZWw1OTk2MjY1NjE=","name":"feature request","description":"New feature or request","color":"a2eeef"},{"id":"MDU6TGFiZWwxMTM5NzQxMjEz","name":"cuDF (Python)","description":"Affects Python cuDF API.","color":"1d76db"}],"milestone":null,"number":5550,"projectCards":[{"project":{"name":"Feature Planning"},"column":{"name":"Needs prioritizing"}}],"projectItems":[],"reactionGroups":[],"state":"OPEN","title":"[FEA] cuDF doesn't work out of the box with `NamedTuple` when constructing a `DataFrame`","updatedAt":"2024-02-23T18:42:53Z","url":"https://github.com/rapidsai/cudf/issues/5550"}
